<?php
if (! $this->helper('Photofancy\Theme\Helper\Config')->get('photofancy_cookiefirst_settings/photofancy_cookiefirst_settings_general/pf_cookiefirst_activated')) {
    return;
}
?>

<script src="https://consent.cookiefirst.com/banner.js"
        data-cookiefirst-key="<?php echo $this->helper('Photofancy\Theme\Helper\Config')->get('photofancy_cookiefirst_settings/photofancy_cookiefirst_settings_general/pf_cookiefirst_api_key'); ?>"></script>

