<?php
// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */
$_order = $block->getOrder();

if ($_order->getStore()->getCode() !== 'storeview_at' || $_order->getPayment()->getMethod() !== 'banktransfer') {
    return false;
}
?>

<table style="padding-bottom:5px; padding-top:20px; width: 100%">
    <tbody>
    <tr>
        <td style="margin-left: 0">
            <p>
                Deine Bestellung wird erst nach erfolgtem Zahlungseingang bearbeitet. Die Produktion/Lieferzeit beginnt 2 Werktage nach Erteilung des Zahlungsauftrags an das überweisende Kreditinstitut.
            </p>

            <p>
                Überweise bitte den Rechnungsbetrag in Höhe von <strong><?= /* @escapeNotVerified */  $_order->formatPriceTxt($_order->getGrandTotal()) ?></strong> auf folgendes Konto:
            </p>

            <p>
                PhotoFancy GmbH<br>
                Deutsche Bank Essen<br>
                <strong>IBAN-Nummer: DE36360700240491699503</strong><br>
                BIC-Code: DEUTDEDBESS<br>
                Verwendungszweck: Bestellung Nr. <strong><?= /* @escapeNotVerified */  $_order->getRealOrderId() ?></strong>
            </p>
        </td>
    </tr>
    </tbody>
</table>
