<?php /** @var Trustedshops\Trustedshops\Block\Selector $block */ ?>
<?php if (($block->isActive() && $block->isExpert())) : ?>
    <script type="text/javascript">
        require(['jquery'], function (jQuery) {

            var waitForEl = function (selector, callback) {
                if (jQuery(selector).length) {
                    callback();
                } else {
                    setTimeout(function () {
                        waitForEl(selector, callback);
                    }, 1);
                }
            };
            jQuery(document).ready(function ($) {
                var ratingStarsEl = '.ts-rating-light.ts-rating.productreviewsSummary';
                var productReviewsEl = '.ts-rating-light.ts-rating.productreviews';
                var customerReviewsEl = '.ts-rating-light.ts-rating.skyscraper_vertical, .ts-rating-light.ts-rating.skyscraper_horizontal, .ts-rating-light.ts-rating.vertical, .ts-rating-light.ts-rating.testimonial';

                // if () {
                //     waitForEl(ratingStarsEl, function () {
                //         $(ratingStarsEl).appendTo('{$sTrustedShops.reviewStarsSelector}');
                //     });
                // }
                // if ('{$sTrustedShops.reviewStickerSelector}') {
                //     waitForEl(productReviewsEl, function () {
                //         $(productReviewsEl).appendTo('{$sTrustedShops.reviewStickerSelector}');
                //     });
                // }
                if ('<?= $block->getReviewStickerSelector() ?>') {
                    waitForEl(customerReviewsEl, function () {
                        jQuery(customerReviewsEl).appendTo('<?= $block->getReviewStickerSelector() ?>');
                    });
                }
            });
        });
    </script>

<?php endif; ?>
