<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Sales\Block\Order\Email\Items\DefaultItems */

/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
$prodImg = $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail');

$options = $_item->getProductOptions();

if ($options['info_buyRequest']) {
    try {
        $prodImg = $options['info_buyRequest']['g3d'][0]['thumbnails'][0]['url'];
    } catch (Exception $exception) {
        // Handle Exception
    }
}
?>
<tr>
    <?php if ($prodImg) : ?>
        <td style="padding: 0 10px 0 0;">
            <img class="photo image"
                 src="<?= /* @escapeNotVerified */ is_object($prodImg) ? $prodImg->getImageUrl() : $prodImg?>"
                 width="100"
                 alt="<?= $block->escapeHtml($_item->getName()) ?>" />
        </td>
    <?php endif; ?>
    <td class="item-info<?php if ($block->getItemOptions()) : ?> has-extra<?php endif; ?>">
        <p class="product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
        <p class="sku"><?= $block->escapeHtml($block->getSku($_item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <?php if ($option['label'] !== "Personalisation Ref") : ?>
                        <p style="color: #aaaaaa"><?= /* @escapeNotVerified */  $option['label'] ?>: <?= /* @escapeNotVerified */  nl2br($option['value']) ?></p>
                    <?php endif; ?>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $eddHelper = $objectManager->get('\Wyomind\EstimatedDeliveryDate\Helper\Data');
        echo $eddHelper->getItemEstimatedDeliveryDate($_item);
        ?>
    </td>
    <td class="item-qty"><?= /* @escapeNotVerified */  $_item->getQtyOrdered() * 1 ?></td>
    <td class="item-price">
        <?= /* @escapeNotVerified */  $block->getItemPrice($_item); ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                        <strong><?= /* @escapeNotVerified */  __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br /><strong><?= /* @escapeNotVerified */  __('Message:'); ?></strong>
                        <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
