<?php
// @codingStandardsIgnoreFile

$_item = $block->getItem();
$_order = $block->getItem()->getInvoice()->getOrder();
$prodImg = $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail');

$options = $_item->getOrderItem()->getProductOptions();

if ($options['info_buyRequest']) {
    try {
        $prodImg = $options['info_buyRequest']['g3d'][0]['thumbnails'][0]['url'];
    } catch (Exception $exception) {
        // Handle Exception
    }
}
?>
<tr>
    <?php if ($prodImg) :?>
        <td class="img" style="width: 140px; border-top: 0 none !important; padding: 35px 10px; border-bottom: 1px dotted #000000;">
            <img class="photo image"
                 src="<?= /* @escapeNotVerified */ is_object($prodImg) ? $prodImg->getImageUrl() : $prodImg?>"
                 width="100"
                 alt="<?= $block->escapeHtml($_item->getName()) ?>" />
        </td>
    <?php endif; ?>
    <td class="item-info<?php if ($block->getItemOptions()): ?> has-extra<?php endif; ?>" colspan="2" style="position: relative !important; border-top: 0 none !important; padding: 35px 10px; border-bottom: 1px dotted #000000;">
        <p class="item-name" style="margin-top: 0 !important;"><?= $block->escapeHtml($_item->getName()) ?></p>
        <div class="item-detail" style="margin: 5px 0; font-size: 12px;">
            <p style="color: #aaaaaa"><?= /* @escapeNotVerified */  __('Item') ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
            <?php if ($block->getItemOptions()): ?>
                <?php foreach ($block->getItemOptions() as $option): ?>
                    <?php if ($option['label'] !== "Personalisation Ref"): ?>
                        <p style="color: #aaaaaa"><?= /* @escapeNotVerified */  $option['label'] ?>: <?= /* @escapeNotVerified */  nl2br($option['value']) ?></p>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?= $addInfoBlock->setItem($_item->getOrderItem())->toHtml() ?>
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
            <p style="color: #aaaaaa"> &nbsp; </p>
        </div>
        <div class="item-price" style="position: absolute !important; bottom: 15px; text-align: left !important; margin-bottom: 25px !important">
            <p><?= is_object($_order) ? $_order->formatPrice($_item->getOrderItem()->getPrice()) : $_item->getOrderItem()->getPrice(); ?> x <?= /* @escapeNotVerified */  $_item->getQty() * 1 ?></p>
        </div>
    </td>
    <td class="item-subtotal" style="vertical-align: bottom; text-align: right; border-top: 0 none !important; padding: 40px 10px; border-bottom: 1px dotted #000000;">
        <p><?= /* @escapeNotVerified */  $block->getItemPrice($_item->getOrderItem()) ?></p>
    </td>
</tr>
