<?php /** @var $block \Photofancy\Editor\Block\Editor */ ?>

<div class="content">

    <h2>Photoeditor SDK</h2>

    <p>
        <?php echo $block->sayHello(); ?>
    </p>

</div>

<div class="wrapper">
    <div class="editorContainer">

        <!--<iframe src="https://local.photofancy.de/app_dev.php/editor?magento=1" width="100%" height="100%" frameborder="0" scrolling="no" allowfullscreen=""></iframe>-->

    </div>

</div>

<script type="text/javascript">
    /*require(['editorServices']);*/
</script>
