<li class="first-child">
    <a href="<?= $block->escapeHtml($block->getData('uri')) ?>">
        <img src="<?= $block->escapeHtml($block->getData('image')) ?>" alt="<?= $block->escapeHtml($block->getData('img-alt')) ?>" title="<?= $block->escapeHtml($block->getData('img-title')) ?>" class="img-hover" style="opacity: 1;">
        <span class="text-hover"><?= $block->escapeHtml($block->getData('label')) ?></span>
    </a>
</li>




<div class="promo">
    <div class="promo-image"><a><img src="{{media url=&quot;wysiwyg/photofancy/Kategoriebilder/wandbilder-mit-eigenem-foto.jpg&quot;}}" alt=""></a>
        <div class="promo-overlay upper hidden-xs">&nbsp;</div>
        <div class="title-v2">
            <div class="buttons"><a class="action primary" href="/produkte.html" target="_self"> zu den Fotogeschenken</a></div>
        </div>
    </div>
</div>
