<?php /** @var $this Trustedshops\Trustedshops\Block\Customer\Form\Edit */ ?>
<div class="col-mp mp-12">
    <input type="checkbox" name="trustedshops_mails_accepted" id="customer-account-edit-trustedshops-mails-accepted" <?= $this->getCheckboxState() ? "checked" : "" ?>/>
    <label for="customer-account-edit-trustedshops-mails-accepted">
        <span>
            <?= __("I would like to receive a review invite by e-mail from Trusted Shops after each purchase. I can revoke my consent at any time.")?>
        </span>
    </label>
</div>
